export type EmojiEntry = {
  emoji: string;
  label: string;
  keywords: string[];
};

export const EMOJIS: EmojiEntry[] = [
  // ── Ansikten & känslor ──────────────────────────────────────────
  { emoji: "😀", label: "Glad", keywords: ["glad", "lycklig", "leende"] },
  { emoji: "😁", label: "Stort leende", keywords: ["glad", "lycklig", "glatt"] },
  { emoji: "😂", label: "Skratt", keywords: ["skratta", "rolig", "haha"] },
  { emoji: "🤣", label: "Rullar av skratt", keywords: ["skratt", "rolig", "lol"] },
  { emoji: "😊", label: "Blyg glad", keywords: ["glad", "söt", "varm"] },
  { emoji: "😍", label: "Förälskad", keywords: ["kärlek", "älska", "förälskad"] },
  { emoji: "🥰", label: "Gullig", keywords: ["söt", "gullig", "hjärtan"] },
  { emoji: "😘", label: "Kyss", keywords: ["kyss", "puss", "kärlek"] },
  { emoji: "😎", label: "Cool", keywords: ["cool", "solglasögon", "häftig"] },
  { emoji: "🤩", label: "Stjärnögon", keywords: ["wow", "imponerad", "häftig", "stjärnögon"] },
  { emoji: "🥳", label: "Firar", keywords: ["fest", "fira", "födelsedag"] },
  { emoji: "😢", label: "Ledsen", keywords: ["ledsen", "gråta", "sorgsen"] },
  { emoji: "😭", label: "Gråter", keywords: ["gråter", "ledsen", "sorgsen"] },
  { emoji: "😤", label: "Frustrerad", keywords: ["frustrerad", "arg", "irriterad"] },
  { emoji: "😡", label: "Arg", keywords: ["arg", "ilsken", "irriterad"] },
  { emoji: "🤬", label: "Mycket arg", keywords: ["arg", "rasande", "ilsken"] },
  { emoji: "😱", label: "Chockad", keywords: ["chockad", "skrämd", "förvånad"] },
  { emoji: "😨", label: "Rädd", keywords: ["rädd", "skrämd", "rädsla"] },
  { emoji: "😰", label: "Orolig", keywords: ["orolig", "svettig", "nervös"] },
  { emoji: "😴", label: "Trött", keywords: ["trött", "sova", "sömnig"] },
  { emoji: "🤒", label: "Sjuk", keywords: ["sjuk", "feber", "magont"] },
  { emoji: "🤢", label: "Illamående", keywords: ["illamående", "sjuk", "kräk"] },
  { emoji: "🤧", label: "Förkyld", keywords: ["förkyld", "snuva", "sjuk", "nys"] },
  { emoji: "🤕", label: "Skadat", keywords: ["skadat", "sjuk", "bandage"] },
  { emoji: "😇", label: "Ängel", keywords: ["ängel", "snäll", "oskyldig"] },
  { emoji: "🤗", label: "Kram", keywords: ["kram", "varm", "omfamna"] },
  { emoji: "🤔", label: "Tänker", keywords: ["tänker", "funderar", "hmm"] },
  { emoji: "🙄", label: "Ögonvridning", keywords: ["trött", "nej", "whatever"] },
  { emoji: "😬", label: "Grimas", keywords: ["grimas", "obekväm", "awkward"] },
  { emoji: "😑", label: "Uttryckslös", keywords: ["uttryckslös", "trött", "stressad"] },
  { emoji: "🥱", label: "Gäspar", keywords: ["gäspar", "trött", "uttråkad"] },
  { emoji: "😏", label: "Smilande", keywords: ["nöjd", "listig", "smug"] },
  { emoji: "🙃", label: "Uppochnervänd", keywords: ["rolig", "ironi", "skämtsam"] },
  { emoji: "😅", label: "Nervöst skratt", keywords: ["nervös", "puh", "oj"] },
  { emoji: "🫠", label: "Smälter", keywords: ["smälter", "varm", "stressad"] },
  { emoji: "🥺", label: "Tigger", keywords: ["tigger", "snälla", "sorgsen"] },

  // ── Händer & gester ─────────────────────────────────────────────
  { emoji: "👍", label: "Tumme upp", keywords: ["bra", "okej", "godkänd", "ja", "hand", "händer"] },
  { emoji: "👎", label: "Tumme ner", keywords: ["dåligt", "nej", "avslag", "hand", "händer"] },
  { emoji: "👏", label: "Applåd", keywords: ["applåd", "bra jobbat", "klappa", "hand", "händer"] },
  { emoji: "🙌", label: "Händer upp", keywords: ["fira", "ja", "hurra", "hand", "händer"] },
  { emoji: "🙏", label: "Tack", keywords: ["tack", "be", "snälla", "hand", "händer"] },
  { emoji: "🤝", label: "Handslag", keywords: ["handslag", "möte", "avtal", "hand", "händer"] },
  { emoji: "✌️", label: "V-tecken", keywords: ["seger", "fred", "v-tecken", "hand", "händer"] },
  { emoji: "👋", label: "Vinka", keywords: ["hej", "hejdå", "vinka", "hand", "händer"] },
  { emoji: "🤙", label: "Ring mig", keywords: ["ring", "telefon", "cool", "hand", "händer"] },
  { emoji: "☝️", label: "Peka upp", keywords: ["peka", "upp", "viktigt", "hand", "händer", "finger"] },
  { emoji: "👆", label: "Peka upp", keywords: ["peka", "upp", "hand", "händer", "finger"] },
  { emoji: "👇", label: "Peka ner", keywords: ["peka", "ner", "hand", "händer", "finger"] },
  { emoji: "👈", label: "Peka vänster", keywords: ["peka", "vänster", "hand", "händer", "finger"] },
  { emoji: "👉", label: "Peka höger", keywords: ["peka", "höger", "hand", "händer", "finger"] },
  { emoji: "🖐️", label: "Öppen hand", keywords: ["stopp", "fem", "hand", "händer", "öppen"] },
  { emoji: "✋", label: "Stopp", keywords: ["stopp", "halt", "hand", "händer"] },
  { emoji: "🤚", label: "Handbaksida", keywords: ["hand", "händer", "baksida"] },
  { emoji: "👌", label: "OK", keywords: ["ok", "okej", "perfekt", "hand", "händer", "finger"] },
  { emoji: "🤌", label: "Knip", keywords: ["knip", "italian", "perfekt", "hand", "händer"] },
  { emoji: "🤞", label: "Korsade fingrar", keywords: ["tur", "lycka", "hoppas", "hand", "händer", "finger"] },
  { emoji: "🤟", label: "Kärlek", keywords: ["kärlek", "rock", "hand", "händer"] },
  { emoji: "🤘", label: "Rock", keywords: ["rock", "metall", "hand", "händer"] },
  { emoji: "🖖", label: "Vulkanhälsning", keywords: ["star trek", "fred", "hand", "händer"] },
  { emoji: "✊", label: "Knytnäve", keywords: ["knytnäve", "styrka", "hand", "händer"] },
  { emoji: "👊", label: "Punch", keywords: ["punch", "slag", "hand", "händer"] },
  { emoji: "🤜", label: "Knytnäve höger", keywords: ["knytnäve", "hand", "händer"] },
  { emoji: "🤛", label: "Knytnäve vänster", keywords: ["knytnäve", "hand", "händer"] },
  { emoji: "👐", label: "Öppna händer", keywords: ["öppna", "fria", "hand", "händer"] },
  { emoji: "🤲", label: "Ihoplagda händer", keywords: ["ihop", "be", "hand", "händer"] },
  { emoji: "🫶", label: "Hjärthand", keywords: ["kärlek", "hjärta", "hand", "händer"] },
  { emoji: "🫰", label: "Fingerknäpp", keywords: ["knäpp", "finger", "hand", "händer"] },
  { emoji: "🫱", label: "Högerhand", keywords: ["höger", "hand", "händer"] },
  { emoji: "🫲", label: "Vänsterhand", keywords: ["vänster", "hand", "händer"] },
  { emoji: "🫳", label: "Handflata ner", keywords: ["handflata", "ner", "hand", "händer"] },
  { emoji: "🫴", label: "Handflata upp", keywords: ["handflata", "upp", "hand", "händer"] },
  { emoji: "💪", label: "Stark arm", keywords: ["stark", "muskel", "träning", "styrka", "arm", "hand"] },

  // ── Hjärtan & symboler ──────────────────────────────────────────
  { emoji: "❤️", label: "Hjärta", keywords: ["hjärta", "kärlek", "röd"] },
  { emoji: "🧡", label: "Orange hjärta", keywords: ["hjärta", "orange"] },
  { emoji: "💛", label: "Gult hjärta", keywords: ["hjärta", "gul"] },
  { emoji: "💚", label: "Grönt hjärta", keywords: ["hjärta", "grön"] },
  { emoji: "💙", label: "Blått hjärta", keywords: ["hjärta", "blå"] },
  { emoji: "💜", label: "Lila hjärta", keywords: ["hjärta", "lila"] },
  { emoji: "🖤", label: "Svart hjärta", keywords: ["hjärta", "svart"] },
  { emoji: "🤍", label: "Vitt hjärta", keywords: ["hjärta", "vit"] },
  { emoji: "💔", label: "Krossat hjärta", keywords: ["hjärta", "krossat", "ledsen"] },
  { emoji: "💕", label: "Två hjärtan", keywords: ["hjärtan", "kärlek"] },
  { emoji: "💞", label: "Snurrande hjärtan", keywords: ["hjärtan", "kärlek"] },
  { emoji: "⭐", label: "Stjärna", keywords: ["stjärna", "guld", "bra"] },
  { emoji: "🌟", label: "Glänsande stjärna", keywords: ["stjärna", "glittra"] },
  { emoji: "✨", label: "Glitter", keywords: ["glitter", "magi", "skinande"] },
  { emoji: "💫", label: "Snurrande stjärna", keywords: ["stjärna", "yr", "svindel"] },
  { emoji: "💥", label: "Explosion", keywords: ["boom", "smäll", "explosion"] },
  { emoji: "🔥", label: "Eld", keywords: ["eld", "brand", "het", "fire"] },
  { emoji: "💯", label: "Hundra procent", keywords: ["perfekt", "hundra", "bra jobbat"] },
  { emoji: "✅", label: "Bockad", keywords: ["klar", "bocka", "godkänd", "färdig"] },
  { emoji: "❌", label: "Fel", keywords: ["fel", "nej", "x"] },
  { emoji: "⚠️", label: "Varning", keywords: ["varning", "obs", "viktigt"] },
  { emoji: "🔔", label: "Klocka", keywords: ["klocka", "notis", "pinga"] },
  { emoji: "🔕", label: "Tyst", keywords: ["tyst", "ingen notis", "mute"] },

  // ── Fest & firande ──────────────────────────────────────────────
  { emoji: "🎉", label: "Konfetti", keywords: ["konfetti", "fest", "fira"] },
  { emoji: "🎊", label: "Festboll", keywords: ["fest", "fira", "ballong"] },
  { emoji: "🎈", label: "Ballong", keywords: ["ballong", "fest", "fira"] },
  { emoji: "🎁", label: "Present", keywords: ["present", "gåva", "födelsedag"] },
  { emoji: "🎀", label: "Rosett", keywords: ["rosett", "band", "present"] },
  { emoji: "🎂", label: "Tårta", keywords: ["tårta", "födelsedag", "ljus"] },
  { emoji: "🧁", label: "Muffin", keywords: ["muffin", "kaka", "fika"] },
  { emoji: "🪅", label: "Piñata", keywords: ["piñata", "fest", "rolig"] },
  { emoji: "🎆", label: "Fyrverkeri", keywords: ["fyrverkeri", "nyår", "fest"] },
  { emoji: "🎇", label: "Tomtebloss", keywords: ["tomtebloss", "nyår", "sparkler"] },
  { emoji: "🧨", label: "Smällare", keywords: ["smällare", "fyrverkeri", "nyår"] },

  // ── Mat – måltider & rätter ─────────────────────────────────────
  { emoji: "🍳", label: "Stekt ägg", keywords: ["ägg", "steka", "frukost"] },
  { emoji: "🥚", label: "Ägg", keywords: ["ägg", "rå", "frukost"] },
  { emoji: "🥞", label: "Pannkakor", keywords: ["pannkakor", "frukost", "plättar"] },
  { emoji: "🧇", label: "Våffla", keywords: ["våffla", "frukost", "söt"] },
  { emoji: "🥓", label: "Bacon", keywords: ["bacon", "frukost", "grillat"] },
  { emoji: "🍞", label: "Bröd", keywords: ["bröd", "limpa", "frukost"] },
  { emoji: "🥐", label: "Croissant", keywords: ["croissant", "franska", "frukost"] },
  { emoji: "🧈", label: "Smör", keywords: ["smör", "bröd", "fett"] },
  { emoji: "🥨", label: "Kringla", keywords: ["kringla", "salt", "snacks"] },
  { emoji: "🧀", label: "Ost", keywords: ["ost", "smörgås", "pizza"] },
  { emoji: "🥗", label: "Sallad", keywords: ["sallad", "hälsa", "grönsaker"] },
  { emoji: "🥙", label: "Kebab", keywords: ["kebab", "pita", "mat"] },
  { emoji: "🌯", label: "Wrap", keywords: ["wrap", "burritos", "mat"] },
  { emoji: "🥪", label: "Smörgås", keywords: ["smörgås", "macka", "lunch"] },
  { emoji: "🍕", label: "Pizza", keywords: ["pizza", "mat"] },
  { emoji: "🍔", label: "Hamburgare", keywords: ["hamburgare", "burger", "snabbmat"] },
  { emoji: "🍟", label: "Pommes frites", keywords: ["pommes", "frites", "snabbmat"] },
  { emoji: "🌮", label: "Taco", keywords: ["taco", "mat", "mexikansk"] },
  { emoji: "🍜", label: "Nudlar", keywords: ["nudlar", "soppa", "asiatisk"] },
  { emoji: "🍝", label: "Pasta", keywords: ["pasta", "spagetti", "italiensk"] },
  { emoji: "🍛", label: "Curry", keywords: ["curry", "ris", "indisk"] },
  { emoji: "🍲", label: "Gryta", keywords: ["gryta", "soppa", "varm mat"] },
  { emoji: "🥘", label: "Paella", keywords: ["paella", "ris", "spansk"] },
  { emoji: "🍣", label: "Sushi", keywords: ["sushi", "japansk", "fisk"] },
  { emoji: "🍱", label: "Matlåda", keywords: ["matlåda", "lunch", "japansk"] },
  { emoji: "🍤", label: "Räkor", keywords: ["räkor", "skaldjur", "stekt"] },
  { emoji: "🦐", label: "Räka", keywords: ["räka", "skaldjur", "hav"] },
  { emoji: "🦞", label: "Hummer", keywords: ["hummer", "skaldjur", "lyx"] },
  { emoji: "🐟", label: "Fisk", keywords: ["fisk", "hav", "mat"] },
  { emoji: "🍗", label: "Kycklingklubba", keywords: ["kyckling", "mat", "grillat"] },
  { emoji: "🥩", label: "Kött", keywords: ["kött", "biff", "mat", "grillat"] },
  { emoji: "🌭", label: "Korv", keywords: ["korv", "varmkorv", "grillkorv"] },
  { emoji: "🥫", label: "Konservburk", keywords: ["konserv", "burk", "mat"] },
  { emoji: "🫙", label: "Glasburk", keywords: ["sylt", "glasburk", "förvaring"] },
  { emoji: "🍽️", label: "Mat", keywords: ["mat", "äta", "middag", "lunch"] },

  // ── Mat – godis & bakverk ───────────────────────────────────────
  { emoji: "🍰", label: "Tårtbit", keywords: ["tårta", "kaka", "bakelse"] },
  { emoji: "🍩", label: "Munk", keywords: ["munk", "donut", "kaka", "söt"] },
  { emoji: "🍪", label: "Kaka", keywords: ["kaka", "cookie", "godis", "söt"] },
  { emoji: "🍫", label: "Choklad", keywords: ["choklad", "godis", "söt"] },
  { emoji: "🍬", label: "Karamell", keywords: ["karamell", "godis", "söt"] },
  { emoji: "🍭", label: "Klubba", keywords: ["klubba", "godis", "söt", "lollipop"] },
  { emoji: "🍦", label: "Softglass", keywords: ["glass", "softglass", "dessert", "sommar"] },
  { emoji: "🍧", label: "Sorbet", keywords: ["sorbet", "glass", "dessert"] },
  { emoji: "🍨", label: "Glass", keywords: ["glass", "dessert", "sommar"] },
  { emoji: "🧆", label: "Falafel", keywords: ["falafel", "vegetarisk", "mat"] },
  { emoji: "🫓", label: "Flatbröd", keywords: ["flatbröd", "bröd", "mat"] },

  // ── Mat – frukt & grönsaker ─────────────────────────────────────
  { emoji: "🍎", label: "Äpple", keywords: ["äpple", "frukt", "röd"] },
  { emoji: "🍊", label: "Apelsin", keywords: ["apelsin", "citrus", "frukt"] },
  { emoji: "🍋", label: "Citron", keywords: ["citron", "syrlig", "frukt"] },
  { emoji: "🍌", label: "Banan", keywords: ["banan", "frukt", "gul"] },
  { emoji: "🍉", label: "Vattenmelon", keywords: ["vattenmelon", "sommar", "frukt"] },
  { emoji: "🍇", label: "Druvor", keywords: ["druvor", "bär", "frukt"] },
  { emoji: "🍓", label: "Jordgubbe", keywords: ["jordgubbe", "bär", "frukt"] },
  { emoji: "🫐", label: "Blåbär", keywords: ["blåbär", "bär", "frukt"] },
  { emoji: "🍒", label: "Körsbär", keywords: ["körsbär", "bär", "röd"] },
  { emoji: "🍑", label: "Persika", keywords: ["persika", "frukt", "sommar"] },
  { emoji: "🥭", label: "Mango", keywords: ["mango", "tropisk", "frukt"] },
  { emoji: "🍍", label: "Ananas", keywords: ["ananas", "tropisk", "frukt"] },
  { emoji: "🥝", label: "Kiwi", keywords: ["kiwi", "grön", "frukt"] },
  { emoji: "🍐", label: "Päron", keywords: ["päron", "frukt", "grön"] },
  { emoji: "🫒", label: "Oliv", keywords: ["oliv", "grön", "mat"] },
  { emoji: "🥕", label: "Morot", keywords: ["morot", "grönsak", "hälsa"] },
  { emoji: "🥦", label: "Broccoli", keywords: ["broccoli", "grönsak", "hälsa"] },
  { emoji: "🥑", label: "Avokado", keywords: ["avokado", "mat", "hälsa"] },
  { emoji: "🌽", label: "Majs", keywords: ["majs", "grönsak", "sommar"] },
  { emoji: "🥔", label: "Potatis", keywords: ["potatis", "grönsak", "mat"] },
  { emoji: "🍆", label: "Aubergine", keywords: ["aubergine", "grönsak", "lila"] },
  { emoji: "🫑", label: "Paprika", keywords: ["paprika", "grönsak", "röd"] },
  { emoji: "🥒", label: "Gurka", keywords: ["gurka", "grönsak", "grön"] },
  { emoji: "🥬", label: "Salladsblad", keywords: ["sallad", "grönsak", "hälsa"] },
  { emoji: "🧅", label: "Lök", keywords: ["lök", "grönsak", "mat"] },
  { emoji: "🧄", label: "Vitlök", keywords: ["vitlök", "grönsak", "smak"] },
  { emoji: "🍄", label: "Svamp", keywords: ["svamp", "skog", "mat"] },
  { emoji: "🫛", label: "Ärtor", keywords: ["ärtor", "baljväxt", "grönsak"] },

  // ── Dryck ────────────────────────────────────────────────────────
  { emoji: "☕", label: "Kaffe", keywords: ["kaffe", "fika", "morgon"] },
  { emoji: "🍵", label: "Te", keywords: ["te", "varm", "fika"] },
  { emoji: "🫖", label: "Tekanna", keywords: ["te", "kanna", "varm dryck"] },
  { emoji: "🥛", label: "Mjölk", keywords: ["mjölk", "dryck", "barn"] },
  { emoji: "🧃", label: "Juice", keywords: ["juice", "dryck", "barn"] },
  { emoji: "🥤", label: "Läsk", keywords: ["läsk", "dryck", "cola"] },
  { emoji: "🧋", label: "Bubbelte", keywords: ["bubbelte", "boba", "dryck"] },
  { emoji: "💧", label: "Vatten", keywords: ["vatten", "droppe", "dricka"] },
  { emoji: "🧊", label: "Is", keywords: ["is", "kall", "isbit"] },
  { emoji: "🍺", label: "Öl", keywords: ["öl", "dryck", "skål"] },
  { emoji: "🍻", label: "Skål", keywords: ["skål", "öl", "fira"] },
  { emoji: "🥂", label: "Champagne", keywords: ["champagne", "skål", "firande"] },
  { emoji: "🍷", label: "Vin", keywords: ["vin", "rödvin", "vitt vin"] },
  { emoji: "🍸", label: "Cocktail", keywords: ["cocktail", "dryck", "fest"] },
  { emoji: "🧉", label: "Mate", keywords: ["mate", "dryck", "sydamerika"] },

  // ── Hygien & hemmarutiner ────────────────────────────────────────
  { emoji: "🚿", label: "Dusch", keywords: ["dusch", "duscha", "tvätta", "hygien", "bad", "dush"] },
  { emoji: "🛁", label: "Badkar", keywords: ["badkar", "bad", "bada", "hygien"] },
  { emoji: "🪥", label: "Tandborste", keywords: ["tänderna", "tandborste", "borsta tänder", "hygien"] },
  { emoji: "🧼", label: "Tvål", keywords: ["tvål", "tvätta händer", "hygien", "rengöra"] },
  { emoji: "🧴", label: "Lotion", keywords: ["lotion", "schampo", "kräm", "hår", "hudvård"] },
  { emoji: "🧻", label: "Toalettpapper", keywords: ["toalettpapper", "papper", "toa"] },
  { emoji: "🪒", label: "Rakapparat", keywords: ["raka sig", "rakning", "rakapparat"] },
  { emoji: "💊", label: "Medicin", keywords: ["medicin", "piller", "tablett"] },
  { emoji: "🩺", label: "Stetoskop", keywords: ["läkare", "stetoskop", "hälsa", "doktor"] },
  { emoji: "🩹", label: "Plåster", keywords: ["plåster", "sår", "hälsa"] },
  { emoji: "🧹", label: "Städa", keywords: ["städa", "kvast", "rengöra", "sopa"] },
  { emoji: "🧺", label: "Tvättkorg", keywords: ["tvätta", "kläder", "tvättmaskin", "smutstvätt"] },
  { emoji: "🧽", label: "Disksvamp", keywords: ["svamp", "diska", "städa", "rengöra"] },
  { emoji: "🫧", label: "Bubblor", keywords: ["bubblor", "tvåla", "rengöra", "städa"] },
  { emoji: "🪣", label: "Hink", keywords: ["hink", "vatten", "städa"] },
  { emoji: "🗑️", label: "Papperskorg", keywords: ["sopor", "kasta", "papperskorg"] },

  // ── Hem & möbler ────────────────────────────────────────────────
  { emoji: "🏠", label: "Hus", keywords: ["hem", "hus", "bostad"] },
  { emoji: "🛏️", label: "Säng", keywords: ["säng", "sova", "sängdags", "lägga sig"] },
  { emoji: "🛋️", label: "Soffa", keywords: ["soffa", "sitta", "vila", "vardagsrum"] },
  { emoji: "🪑", label: "Stol", keywords: ["stol", "sitta", "möbel"] },
  { emoji: "🚪", label: "Dörr", keywords: ["dörr", "öppna", "hem"] },
  { emoji: "🪞", label: "Spegel", keywords: ["spegel", "titta", "spegling"] },
  { emoji: "🪟", label: "Fönster", keywords: ["fönster", "utsikt", "öppen"] },
  { emoji: "🖼️", label: "Tavla", keywords: ["tavla", "konst", "ram"] },

  // ── Skola & lärande ─────────────────────────────────────────────
  { emoji: "🎓", label: "Examen", keywords: ["examen", "skola", "student", "plugg", "universitetet"] },
  { emoji: "🏫", label: "Skola", keywords: ["skola", "utbildning", "barn"] },
  { emoji: "📚", label: "Böcker", keywords: ["böcker", "läsa", "studera", "bibliotek", "plugg"] },
  { emoji: "📖", label: "Öppen bok", keywords: ["läsa", "bok", "studera"] },
  { emoji: "✏️", label: "Penna", keywords: ["penna", "skriva", "rita", "läxor"] },
  { emoji: "📝", label: "Anteckna", keywords: ["anteckna", "skriva", "lista", "läxor"] },
  { emoji: "📏", label: "Linjal", keywords: ["linjal", "mäta", "skola"] },
  { emoji: "📐", label: "Vinkelhake", keywords: ["vinkelhake", "mäta", "skola"] },
  { emoji: "✂️", label: "Sax", keywords: ["sax", "klippa", "slöjd"] },
  { emoji: "🖊️", label: "Kulspetspenna", keywords: ["penna", "skriva", "signera"] },
  { emoji: "📌", label: "Nål", keywords: ["nål", "markera", "viktigt"] },
  { emoji: "🔍", label: "Förstoringsglas", keywords: ["sök", "hitta", "förstora"] },
  { emoji: "🗂️", label: "Mapp", keywords: ["mapp", "organisera", "filer"] },

  // ── Arbete & produktivitet ──────────────────────────────────────
  { emoji: "💻", label: "Dator", keywords: ["dator", "laptop", "jobba", "arbete"] },
  { emoji: "🖥️", label: "Skärm", keywords: ["dator", "skärm", "arbete"] },
  { emoji: "📱", label: "Telefon", keywords: ["telefon", "mobil", "ring"] },
  { emoji: "⌨️", label: "Tangentbord", keywords: ["tangentbord", "skriva", "dator"] },
  { emoji: "🖨️", label: "Skrivare", keywords: ["skrivare", "printa", "papper"] },
  { emoji: "📷", label: "Kamera", keywords: ["kamera", "foto", "fotografera"] },
  { emoji: "⏰", label: "Väckarklocka", keywords: ["klocka", "tid", "alarm", "morgon", "vakna"] },
  { emoji: "📅", label: "Kalender", keywords: ["kalender", "datum", "schema"] },
  { emoji: "🗓️", label: "Planeringskalender", keywords: ["kalender", "planering", "schema"] },
  { emoji: "📊", label: "Diagram", keywords: ["diagram", "data", "rapport"] },
  { emoji: "📋", label: "Checklista", keywords: ["lista", "checklista", "rapport"] },
  { emoji: "💼", label: "Portfölj", keywords: ["arbete", "jobb", "möte", "portfölj"] },
  { emoji: "🔧", label: "Skiftnyckel", keywords: ["reparera", "fixa", "verktyg"] },
  { emoji: "🔨", label: "Hammare", keywords: ["hammare", "bygga", "verktyg", "snickra"] },
  { emoji: "⚙️", label: "Kugghjul", keywords: ["inställningar", "teknik", "mekanism"] },
  { emoji: "🧰", label: "Verktygslåda", keywords: ["verktyg", "reparera", "fixa"] },

  // ── Underhållning & fritid ──────────────────────────────────────
  { emoji: "🎬", label: "Bio", keywords: ["bio", "film", "kino", "biograf", "filmkväll"] },
  { emoji: "🎥", label: "Filmkamera", keywords: ["film", "filma", "video", "bio"] },
  { emoji: "🍿", label: "Popcorn", keywords: ["popcorn", "bio", "film", "kväll"] },
  { emoji: "📺", label: "TV", keywords: ["tv", "titta", "serie", "film", "tevé"] },
  { emoji: "📻", label: "Radio", keywords: ["radio", "musik", "lyssna"] },
  { emoji: "🎙️", label: "Mikrofon", keywords: ["mikrofon", "prata", "podcast", "sjunga"] },
  { emoji: "🎤", label: "Karaoke", keywords: ["karaoke", "sjunga", "sång", "mikrofon"] },
  { emoji: "🎵", label: "Musik", keywords: ["musik", "sång", "noter"] },
  { emoji: "🎶", label: "Noter", keywords: ["musik", "noter", "sång"] },
  { emoji: "🎸", label: "Gitarr", keywords: ["gitarr", "musik", "rock"] },
  { emoji: "🎹", label: "Piano", keywords: ["piano", "musik", "tangenter"] },
  { emoji: "🥁", label: "Trummor", keywords: ["trummor", "musik", "rytm"] },
  { emoji: "🎺", label: "Trumpet", keywords: ["trumpet", "musik", "blåsinstrument"] },
  { emoji: "🎻", label: "Fiol", keywords: ["fiol", "violin", "musik"] },
  { emoji: "🪗", label: "Dragspel", keywords: ["dragspel", "musik", "dans"] },
  { emoji: "🎷", label: "Saxofon", keywords: ["saxofon", "jazz", "musik"] },
  { emoji: "🎮", label: "Spel", keywords: ["spel", "gaming", "datorspel", "spela"] },
  { emoji: "🕹️", label: "Joystick", keywords: ["joystick", "spel", "gaming"] },
  { emoji: "🎲", label: "Tärning", keywords: ["tärning", "brädspel", "spel", "chans"] },
  { emoji: "🃏", label: "Kortspel", keywords: ["kort", "kortspel", "spel"] },
  { emoji: "🧩", label: "Pussel", keywords: ["pussel", "spel", "logik"] },
  { emoji: "🎯", label: "Mål", keywords: ["mål", "träffa", "dart"] },
  { emoji: "🎳", label: "Bowling", keywords: ["bowling", "sport", "käglor"] },
  { emoji: "♟️", label: "Schack", keywords: ["schack", "spel", "strategi"] },
  { emoji: "🎭", label: "Teater", keywords: ["teater", "drama", "skådespel"] },
  { emoji: "🎨", label: "Konst", keywords: ["konst", "måla", "kreativ", "rita"] },
  { emoji: "🖌️", label: "Pensel", keywords: ["pensel", "måla", "konst"] },
  { emoji: "🎪", label: "Cirkus", keywords: ["cirkus", "show", "tält"] },
  { emoji: "🎠", label: "Karusell", keywords: ["karusell", "nöjespark", "barn"] },
  { emoji: "🎡", label: "Pariserhjul", keywords: ["pariserhjul", "nöjespark"] },
  { emoji: "🎢", label: "Berg-och-dalbana", keywords: ["berg-och-dalbana", "nöjespark", "fart"] },
  { emoji: "🧶", label: "Sticka", keywords: ["sticka", "ull", "handarbete"] },
  { emoji: "🪡", label: "Sy", keywords: ["sy", "tråd", "handarbete"] },
  { emoji: "🎣", label: "Fiska", keywords: ["fiska", "fiske", "sjö", "fritid"] },

  // ── Sport & träning ─────────────────────────────────────────────
  { emoji: "⚽", label: "Fotboll", keywords: ["fotboll", "sport", "boll"] },
  { emoji: "🏀", label: "Basket", keywords: ["basket", "sport", "boll"] },
  { emoji: "🏈", label: "Amerikansk fotboll", keywords: ["football", "sport", "boll"] },
  { emoji: "⚾", label: "Baseball", keywords: ["baseball", "sport", "boll"] },
  { emoji: "🎾", label: "Tennis", keywords: ["tennis", "sport", "racket"] },
  { emoji: "🏐", label: "Volleyboll", keywords: ["volleyboll", "sport", "boll"] },
  { emoji: "🏉", label: "Rugby", keywords: ["rugby", "sport", "boll"] },
  { emoji: "🎱", label: "Biljard", keywords: ["biljard", "pool", "spel"] },
  { emoji: "🏸", label: "Badminton", keywords: ["badminton", "sport", "racket"] },
  { emoji: "🏒", label: "Ishockey", keywords: ["hockey", "ishockey", "sport", "is"] },
  { emoji: "🏑", label: "Hockey", keywords: ["hockey", "sport", "pinne"] },
  { emoji: "🥊", label: "Boxning", keywords: ["boxning", "sport", "kampsport"] },
  { emoji: "🥋", label: "Kampsport", keywords: ["kampsport", "judo", "karate"] },
  { emoji: "⛸️", label: "Skridskor", keywords: ["skridskor", "is", "vinter", "åka"] },
  { emoji: "🛷", label: "Spark", keywords: ["spark", "pulka", "vinter", "snö"] },
  { emoji: "🏊", label: "Simning", keywords: ["simma", "bad", "pool", "bassäng", "simhall"] },
  { emoji: "🤽", label: "Vattenpolo", keywords: ["vattenpolo", "simma", "sport"] },
  { emoji: "🚴", label: "Cykling", keywords: ["cykling", "cykel", "träning"] },
  { emoji: "🏃", label: "Löpning", keywords: ["springa", "löpning", "jogga", "träning"] },
  { emoji: "🚶", label: "Gå", keywords: ["gå", "promenad", "gångtur"] },
  { emoji: "🧗", label: "Klättring", keywords: ["klättra", "klättring", "boulder"] },
  { emoji: "🏋️", label: "Gym", keywords: ["gym", "träning", "styrka", "lyfta"] },
  { emoji: "🤸", label: "Gymnastik", keywords: ["gymnastik", "akrobat", "träning"] },
  { emoji: "🤺", label: "Fäktning", keywords: ["fäktning", "sport", "svärd"] },
  { emoji: "🏇", label: "Ridning", keywords: ["ridning", "häst", "sport"] },
  { emoji: "🤾", label: "Handboll", keywords: ["handboll", "sport", "boll"] },
  { emoji: "🏄", label: "Surfing", keywords: ["surfing", "hav", "våg", "sport"] },
  { emoji: "🚣", label: "Rodd", keywords: ["rodd", "båt", "sport", "vatten"] },
  { emoji: "🤿", label: "Dykning", keywords: ["dykning", "snorkel", "hav", "simma"] },
  { emoji: "⛷️", label: "Skidåkning", keywords: ["skida", "ski", "vinter", "fjäll"] },
  { emoji: "🏂", label: "Snowboard", keywords: ["snowboard", "vinter", "snö"] },
  { emoji: "🧘", label: "Yoga", keywords: ["yoga", "meditation", "lugn", "stretcha"] },
  { emoji: "🏕️", label: "Camping", keywords: ["camping", "tält", "friluftsliv", "natur"] },
  { emoji: "🧭", label: "Kompass", keywords: ["kompass", "orientering", "friluftsliv", "navigera"] },

  // ── Resor & transport ────────────────────────────────────────────
  { emoji: "✈️", label: "Flygplan", keywords: ["flyg", "resa", "semester", "utomlands"] },
  { emoji: "🚗", label: "Bil", keywords: ["bil", "köra", "transport", "åka"] },
  { emoji: "🏎️", label: "Racerbil", keywords: ["racerbil", "fart", "racing"] },
  { emoji: "🚕", label: "Taxi", keywords: ["taxi", "bil", "transport"] },
  { emoji: "🚌", label: "Buss", keywords: ["buss", "kollektivtrafik", "åka"] },
  { emoji: "🚎", label: "Trolleybus", keywords: ["trolleybus", "buss", "kollektivtrafik"] },
  { emoji: "🚂", label: "Tåg", keywords: ["tåg", "järnväg", "resa"] },
  { emoji: "🚇", label: "Tunnelbana", keywords: ["tunnelbana", "metro", "kollektivtrafik"] },
  { emoji: "🚃", label: "Spårvagn", keywords: ["spårvagn", "tram", "kollektivtrafik"] },
  { emoji: "🚢", label: "Båt", keywords: ["båt", "kryssning", "hav", "färja"] },
  { emoji: "⛵", label: "Segelbåt", keywords: ["segelbåt", "segla", "hav"] },
  { emoji: "🚤", label: "Motorbåt", keywords: ["motorbåt", "fart", "hav"] },
  { emoji: "🛶", label: "Kano", keywords: ["kano", "padda", "sjö"] },
  { emoji: "🚁", label: "Helikopter", keywords: ["helikopter", "flyg", "räddning"] },
  { emoji: "🚀", label: "Raket", keywords: ["raket", "rymden", "space"] },
  { emoji: "🛸", label: "UFO", keywords: ["ufo", "rymden", "flygande tefat"] },
  { emoji: "🚲", label: "Cykel", keywords: ["cykel", "cykla", "transport"] },
  { emoji: "🛵", label: "Moped", keywords: ["moped", "scooter", "transport"] },
  { emoji: "🏍️", label: "Motorcykel", keywords: ["motorcykel", "mc", "transport"] },
  { emoji: "🚒", label: "Brandbil", keywords: ["brandbil", "brandkår", "räddning"] },
  { emoji: "🚑", label: "Ambulans", keywords: ["ambulans", "sjukhus", "räddning"] },
  { emoji: "🚓", label: "Polisbil", keywords: ["polis", "polisbil", "lag"] },

  // ── Natur & väder ────────────────────────────────────────────────
  { emoji: "🌞", label: "Sol", keywords: ["sol", "sommar", "värme", "soligt"] },
  { emoji: "⛅", label: "Delvis molnigt", keywords: ["moln", "sol", "väder"] },
  { emoji: "🌧️", label: "Regn", keywords: ["regn", "regnigt", "väder"] },
  { emoji: "⛈️", label: "Åska", keywords: ["åska", "storm", "blixt", "väder"] },
  { emoji: "🌩️", label: "Blixt", keywords: ["blixt", "åska", "väder"] },
  { emoji: "🌨️", label: "Snöoväder", keywords: ["snö", "storm", "vinter"] },
  { emoji: "❄️", label: "Snöflinga", keywords: ["snö", "vinter", "is", "kall"] },
  { emoji: "🌬️", label: "Vind", keywords: ["vind", "blåser", "väder"] },
  { emoji: "🌫️", label: "Dimma", keywords: ["dimma", "grå", "dimmigt"] },
  { emoji: "🌈", label: "Regnbåge", keywords: ["regnbåge", "färger", "regn"] },
  { emoji: "🌙", label: "Måne", keywords: ["måne", "natt", "halvmåne"] },
  { emoji: "🌊", label: "Hav", keywords: ["hav", "ocean", "våg"] },
  { emoji: "🏔️", label: "Berg", keywords: ["berg", "fjäll", "vandring"] },
  { emoji: "🌿", label: "Växt", keywords: ["natur", "växt", "grön", "ört"] },
  { emoji: "🌸", label: "Körsbärsblomma", keywords: ["blomma", "rosa", "vår"] },
  { emoji: "🌺", label: "Hibiskus", keywords: ["blomma", "tropisk", "röd"] },
  { emoji: "🌻", label: "Solros", keywords: ["solros", "blomma", "gul", "sommar"] },
  { emoji: "🌼", label: "Prästkrage", keywords: ["blomma", "gul", "prästkrage"] },
  { emoji: "💐", label: "Bukett", keywords: ["bukett", "blommor", "blomma"] },
  { emoji: "🍀", label: "Klöver", keywords: ["klöver", "tur", "lycka", "fyrbladig"] },
  { emoji: "🍁", label: "Löv", keywords: ["löv", "höst", "orange"] },
  { emoji: "🍂", label: "Fallande löv", keywords: ["löv", "höst", "faller"] },
  { emoji: "🌲", label: "Gran", keywords: ["träd", "skog", "gran"] },
  { emoji: "🌴", label: "Palm", keywords: ["palm", "tropisk", "semester"] },
  { emoji: "🌾", label: "Vete", keywords: ["vete", "åker", "höst", "natur"] },
  { emoji: "🪨", label: "Sten", keywords: ["sten", "klippa", "natur"] },
  { emoji: "🪵", label: "Ved", keywords: ["ved", "trä", "virke"] },

  // ── Djur ─────────────────────────────────────────────────────────
  { emoji: "🐶", label: "Hund", keywords: ["hund", "valp", "vovve", "husdjur"] },
  { emoji: "🐱", label: "Katt", keywords: ["katt", "kattunge", "misse", "husdjur"] },
  { emoji: "🐰", label: "Kanin", keywords: ["kanin", "hare", "husdjur"] },
  { emoji: "🐹", label: "Hamster", keywords: ["hamster", "husdjur", "gnagare"] },
  { emoji: "🐻", label: "Björn", keywords: ["björn", "nallebjörn"] },
  { emoji: "🦁", label: "Lejon", keywords: ["lejon", "safari"] },
  { emoji: "🐯", label: "Tiger", keywords: ["tiger", "safari", "randig"] },
  { emoji: "🐮", label: "Ko", keywords: ["ko", "mjölk", "bondgård"] },
  { emoji: "🐷", label: "Gris", keywords: ["gris", "bondgård", "rosa"] },
  { emoji: "🐔", label: "Höna", keywords: ["höna", "kyckling", "bondgård"] },
  { emoji: "🦆", label: "Anka", keywords: ["anka", "and", "vatten", "fågel"] },
  { emoji: "🦉", label: "Uggla", keywords: ["uggla", "natt", "klok", "fågel"] },
  { emoji: "🦅", label: "Örn", keywords: ["örn", "fågel", "majestätisk"] },
  { emoji: "🦜", label: "Papegoja", keywords: ["papegoja", "fågel", "färgglad"] },
  { emoji: "🐦", label: "Fågel", keywords: ["fågel", "flyg", "kvitter"] },
  { emoji: "🦋", label: "Fjäril", keywords: ["fjäril", "blomma", "vacker", "insekt"] },
  { emoji: "🐝", label: "Bi", keywords: ["bi", "honung", "insekt"] },
  { emoji: "🐛", label: "Larv", keywords: ["larv", "mask", "insekt"] },
  { emoji: "🐞", label: "Nyckelpiga", keywords: ["nyckelpiga", "insekt", "röd"] },
  { emoji: "🐌", label: "Snigel", keywords: ["snigel", "långsam", "trädgård"] },
  { emoji: "🦊", label: "Räv", keywords: ["räv", "listig", "djur"] },
  { emoji: "🐺", label: "Varg", keywords: ["varg", "skog", "djur"] },
  { emoji: "🦌", label: "Hjort", keywords: ["hjort", "rådjur", "skog"] },
  { emoji: "🐘", label: "Elefant", keywords: ["elefant", "stor", "safari"] },
  { emoji: "🦒", label: "Giraff", keywords: ["giraff", "lång hals", "safari"] },
  { emoji: "🦓", label: "Zebra", keywords: ["zebra", "randig", "safari"] },
  { emoji: "🦈", label: "Haj", keywords: ["haj", "fisk", "hav"] },
  { emoji: "🐬", label: "Delfin", keywords: ["delfin", "hav", "smart"] },
  { emoji: "🐳", label: "Val", keywords: ["val", "hav", "stor"] },
  { emoji: "🐢", label: "Sköldpadda", keywords: ["sköldpadda", "långsam", "djur"] },
  { emoji: "🐸", label: "Groda", keywords: ["groda", "grön", "sjö"] },
  { emoji: "🦄", label: "Enhörning", keywords: ["enhörning", "magi", "häst"] },
  { emoji: "🐾", label: "Tassar", keywords: ["tassar", "djur", "hund", "katt"] },

  // ── Platser & byggnader ──────────────────────────────────────────
  { emoji: "🌍", label: "Världen", keywords: ["världen", "jordklot", "jord", "resa", "global"] },
  { emoji: "🏖️", label: "Strand", keywords: ["strand", "semester", "sommar", "bad"] },
  { emoji: "🏥", label: "Sjukhus", keywords: ["sjukhus", "vård", "läkare"] },
  { emoji: "🏰", label: "Slott", keywords: ["slott", "kung", "prinsessa"] },
  { emoji: "⛪", label: "Kyrka", keywords: ["kyrka", "religion", "bröllop"] },
  { emoji: "🏪", label: "Affär", keywords: ["affär", "butik", "handla"] },
  { emoji: "🏬", label: "Varuhus", keywords: ["varuhus", "köpcentrum", "handla"] },
  { emoji: "🏦", label: "Bank", keywords: ["bank", "pengar", "ekonomi"] },
  { emoji: "🏨", label: "Hotell", keywords: ["hotell", "bo", "semester"] },
  { emoji: "🏟️", label: "Stadion", keywords: ["stadion", "sport", "arena"] },
  { emoji: "🌆", label: "Stad", keywords: ["stad", "city", "skyline"] },

  // ── Shopping & ekonomi ───────────────────────────────────────────
  { emoji: "🛒", label: "Kundvagn", keywords: ["handla", "shopping", "affär", "mat", "inköp"] },
  { emoji: "🏷️", label: "Prislapp", keywords: ["pris", "rea", "prislapp"] },
  { emoji: "💰", label: "Pengar", keywords: ["pengar", "säck", "guld", "rik"] },
  { emoji: "💳", label: "Betalkort", keywords: ["kort", "betala", "bank"] },
  { emoji: "🎫", label: "Biljett", keywords: ["biljett", "inträde", "konsert"] },
  { emoji: "🎟️", label: "Inträde", keywords: ["inträde", "biljett", "fest"] },
  { emoji: "🔑", label: "Nyckel", keywords: ["nyckel", "lås", "öppna"] },

  // ── Övrigt & symboler ───────────────────────────────────────────
  { emoji: "💡", label: "Idé", keywords: ["idé", "lampa", "tips", "tanke"] },
  { emoji: "🔦", label: "Ficklampa", keywords: ["ficklampa", "ljus", "mörk"] },
  { emoji: "🕯️", label: "Ljus", keywords: ["ljus", "levande ljus", "romantik"] },
  { emoji: "🧲", label: "Magnet", keywords: ["magnet", "dra", "metall"] },
  { emoji: "📦", label: "Kartong", keywords: ["kartong", "låda", "flytta", "packa"] },
  { emoji: "🎒", label: "Ryggsäck", keywords: ["ryggsäck", "skola", "resa"] },
  { emoji: "👓", label: "Glasögon", keywords: ["glasögon", "se", "läsa"] },
  { emoji: "🎩", label: "Hatt", keywords: ["hatt", "elegant", "magiker"] },
  { emoji: "👒", label: "Solhatt", keywords: ["solhatt", "sommar", "semester"] },
  { emoji: "🧸", label: "Nalle", keywords: ["nalle", "leksak", "barn"] },
  { emoji: "🪆", label: "Matrjosjka", keywords: ["matrjosjka", "rysk", "leksak"] },
  { emoji: "🏆", label: "Trofé", keywords: ["trofé", "vinst", "mästerskap"] },
  { emoji: "🥇", label: "Guld", keywords: ["guld", "etta", "vinnare", "medalj"] },
  { emoji: "🥈", label: "Silver", keywords: ["silver", "tvåa", "medalj"] },
  { emoji: "🥉", label: "Brons", keywords: ["brons", "trea", "medalj"] },
  { emoji: "🎖️", label: "Medalj", keywords: ["medalj", "utmärkelse", "hedra"] },
];
