export type EmojiEntry = {
  emoji: string;
  label: string;
  keywords: string[];
};

export const EMOJIS: EmojiEntry[] = [
  // Ansikten & känslor
  { emoji: "😀", label: "Glad", keywords: ["glad", "lycklig", "skratta", "leende"] },
  { emoji: "😂", label: "Skratt med tårar", keywords: ["skratta", "rolig", "haha", "lol"] },
  { emoji: "😍", label: "Förälskad", keywords: ["kärlek", "älska", "förälskad", "hjärta"] },
  { emoji: "🥰", label: "Söt med hjärtan", keywords: ["kärlek", "söt", "gullig", "hjärtan"] },
  { emoji: "😢", label: "Ledsen", keywords: ["ledsen", "gråta", "sorgsen", "tår"] },
  { emoji: "😡", label: "Arg", keywords: ["arg", "ilsken", "irriterad", "sur"] },
  { emoji: "🥳", label: "Firar", keywords: ["fest", "fira", "födelsedag", "firande"] },
  { emoji: "😴", label: "Trött", keywords: ["trött", "sova", "sömnig", "natt"] },
  { emoji: "🤒", label: "Sjuk", keywords: ["sjuk", "feber", "illa", "magont"] },
  { emoji: "😎", label: "Cool", keywords: ["cool", "solglasögon", "häftig"] },
  { emoji: "🤗", label: "Kram", keywords: ["kram", "kramar", "varm", "omfamna"] },
  { emoji: "🤔", label: "Tänker", keywords: ["tänker", "funderar", "hmm", "kanske"] },

  // Hjärtan & symboler
  { emoji: "❤️", label: "Rött hjärta", keywords: ["hjärta", "kärlek", "röd", "love"] },
  { emoji: "💙", label: "Blått hjärta", keywords: ["hjärta", "blå", "kärlek"] },
  { emoji: "💚", label: "Grönt hjärta", keywords: ["hjärta", "grön", "natur"] },
  { emoji: "💛", label: "Gult hjärta", keywords: ["hjärta", "gul", "kärlek"] },
  { emoji: "🖤", label: "Svart hjärta", keywords: ["hjärta", "svart", "mörk"] },
  { emoji: "⭐", label: "Stjärna", keywords: ["stjärna", "guld", "gul", "bra"] },
  { emoji: "🌟", label: "Lysande stjärna", keywords: ["stjärna", "glittra", "skinande"] },
  { emoji: "✨", label: "Glitter", keywords: ["glitter", "stjärnor", "skinande", "magi"] },
  { emoji: "🎉", label: "Konfetti", keywords: ["konfetti", "fest", "fira", "firande"] },
  { emoji: "🎊", label: "Festboll", keywords: ["fest", "fira", "ballong", "firande"] },
  { emoji: "👍", label: "Tumme upp", keywords: ["bra", "okej", "tumme", "godkänd", "ja"] },
  { emoji: "👎", label: "Tumme ner", keywords: ["dåligt", "nej", "avslag", "tumme"] },
  { emoji: "🙏", label: "Böjda händer", keywords: ["tack", "be", "händer", "snälla", "bön"] },
  { emoji: "🏆", label: "Trofé", keywords: ["trofé", "vinst", "mästerskap", "guld", "vinnare"] },
  { emoji: "🥇", label: "Guldmedalj", keywords: ["guld", "etta", "vinnare", "bäst", "medalj"] },
  { emoji: "💡", label: "Idé", keywords: ["idé", "lampa", "tips", "tanke", "aha"] },

  // Mat & fika
  { emoji: "🍕", label: "Pizza", keywords: ["pizza", "mat", "italiensk"] },
  { emoji: "🍔", label: "Hamburgare", keywords: ["hamburgare", "burger", "mat", "snabbmat"] },
  { emoji: "🌮", label: "Taco", keywords: ["taco", "mat", "mexikansk"] },
  { emoji: "🍣", label: "Sushi", keywords: ["sushi", "mat", "japansk", "fisk"] },
  { emoji: "🍜", label: "Nudlar", keywords: ["nudlar", "soppa", "mat", "asiatisk"] },
  { emoji: "🍰", label: "Tårtbit", keywords: ["tårta", "kaka", "bakelse", "söt"] },
  { emoji: "🎂", label: "Tårta", keywords: ["tårta", "födelsedag", "kaka", "ljus"] },
  { emoji: "🧁", label: "Muffin", keywords: ["muffin", "kaka", "bakelse", "söt", "fika"] },
  { emoji: "🍫", label: "Choklad", keywords: ["choklad", "godis", "söt"] },
  { emoji: "🍦", label: "Glass", keywords: ["glass", "söt", "dessert", "sommar"] },
  { emoji: "🍎", label: "Äpple", keywords: ["äpple", "frukt", "röd", "hälsa"] },
  { emoji: "🍓", label: "Jordgubbe", keywords: ["jordgubbe", "bär", "röd", "frukt", "söt"] },
  { emoji: "🍌", label: "Banan", keywords: ["banan", "frukt", "gul"] },
  { emoji: "🍊", label: "Apelsin", keywords: ["apelsin", "citrus", "frukt", "orange"] },
  { emoji: "🍇", label: "Druvor", keywords: ["druvor", "bär", "frukt", "lila"] },
  { emoji: "🥕", label: "Morot", keywords: ["morot", "grönsak", "orange", "hälsa"] },
  { emoji: "🥦", label: "Broccoli", keywords: ["broccoli", "grönsak", "grön", "hälsa"] },
  { emoji: "🥑", label: "Avokado", keywords: ["avokado", "grön", "mat", "hälsa"] },
  { emoji: "🍳", label: "Stekpanna", keywords: ["ägg", "steka", "laga mat", "frukost"] },
  { emoji: "🥞", label: "Pannkakor", keywords: ["pannkakor", "frukost", "söt", "plättar"] },

  // Dryck
  { emoji: "☕", label: "Kaffe", keywords: ["kaffe", "fika", "morgon", "varm"] },
  { emoji: "🍵", label: "Te", keywords: ["te", "varm", "dryck", "fika"] },
  { emoji: "🧃", label: "Juice", keywords: ["juice", "dryck", "frukt", "barn"] },
  { emoji: "🥛", label: "Mjölk", keywords: ["mjölk", "dryck", "vit", "barn"] },
  { emoji: "🍺", label: "Öl", keywords: ["öl", "alkohol", "dryck"] },
  { emoji: "🥤", label: "Läsk", keywords: ["läsk", "dryck", "sugrör", "cola"] },

  // Aktiviteter & sport
  { emoji: "⚽", label: "Fotboll", keywords: ["fotboll", "sport", "boll", "spela"] },
  { emoji: "🏊", label: "Simning", keywords: ["simma", "simning", "bad", "pool", "bassäng"] },
  { emoji: "🚴", label: "Cykling", keywords: ["cykling", "cykel", "sport", "träning"] },
  { emoji: "🏃", label: "Löpning", keywords: ["springa", "löpning", "jogga", "träning"] },
  { emoji: "🏋️", label: "Styrketräning", keywords: ["gym", "träning", "styrka", "lyfta"] },
  { emoji: "⛷️", label: "Skidåkning", keywords: ["skida", "ski", "vinter", "snö", "fjäll"] },
  { emoji: "🏂", label: "Snowboard", keywords: ["snowboard", "vinter", "snö", "bräda"] },
  { emoji: "🤸", label: "Gymnastik", keywords: ["gymnastik", "akrobatik", "sport", "rörelse"] },
  { emoji: "🧘", label: "Yoga", keywords: ["yoga", "meditation", "lugn", "träning"] },
  { emoji: "🎵", label: "Musik", keywords: ["musik", "sång", "noter", "melodim", "lyssna"] },
  { emoji: "🎸", label: "Gitarr", keywords: ["gitarr", "musik", "rock", "spela"] },
  { emoji: "🎹", label: "Piano", keywords: ["piano", "musik", "tangenter", "spela"] },
  { emoji: "🎮", label: "Spelkontroll", keywords: ["spel", "gaming", "kontroll", "datorspel"] },
  { emoji: "🎭", label: "Teater", keywords: ["teater", "mask", "drama", "skådespel"] },
  { emoji: "🎨", label: "Konst", keywords: ["konst", "måla", "paletten", "kreativ"] },
  { emoji: "🎯", label: "Mål", keywords: ["mål", "pil", "träffa", "boogst", "dart"] },
  { emoji: "🎪", label: "Cirkus", keywords: ["cirkus", "fest", "show", "tält"] },
  { emoji: "🎓", label: "Examen", keywords: ["examen", "skola", "utbildning", "student", "plugg"] },
  { emoji: "🏖️", label: "Strand", keywords: ["strand", "semester", "sommar", "bad", "hav"] },
  { emoji: "📚", label: "Böcker", keywords: ["böcker", "läsa", "studera", "skola", "bibliotek"] },

  // Transport
  { emoji: "✈️", label: "Flygplan", keywords: ["flyg", "resa", "flygplan", "semester"] },
  { emoji: "🚗", label: "Bil", keywords: ["bil", "köra", "transport", "åka"] },
  { emoji: "🚂", label: "Tåg", keywords: ["tåg", "järnväg", "resa", "transport"] },
  { emoji: "🚢", label: "Båt", keywords: ["båt", "kryssning", "hav", "resa", "färja"] },
  { emoji: "🚲", label: "Cykel", keywords: ["cykel", "cykla", "transport"] },
  { emoji: "🚁", label: "Helikopter", keywords: ["helikopter", "flyg", "transport"] },
  { emoji: "🛸", label: "UFO", keywords: ["ufo", "rymdskepp", "rymd", "alien"] },

  // Natur & väder
  { emoji: "🌿", label: "Växt", keywords: ["natur", "växt", "grön", "blad", "ört"] },
  { emoji: "🌸", label: "Körsbärsblomma", keywords: ["blomma", "rosa", "vår", "japan"] },
  { emoji: "🌺", label: "Hibiskus", keywords: ["blomma", "röd", "tropisk"] },
  { emoji: "🌻", label: "Solros", keywords: ["solros", "blomma", "gul", "sommar"] },
  { emoji: "🍀", label: "Klöver", keywords: ["klöver", "tur", "lycka", "grön"] },
  { emoji: "🍁", label: "Löv", keywords: ["löv", "höst", "orange", "träd"] },
  { emoji: "🌲", label: "Träd", keywords: ["träd", "skog", "gran", "natur"] },
  { emoji: "🌴", label: "Palm", keywords: ["palm", "tropisk", "semester", "strand"] },
  { emoji: "🌈", label: "Regnbåge", keywords: ["regnbåge", "färger", "regn", "sol"] },
  { emoji: "🌞", label: "Sol", keywords: ["sol", "sommar", "värme", "solig"] },
  { emoji: "🌙", label: "Måne", keywords: ["måne", "natt", "mörk", "halvmåne"] },
  { emoji: "❄️", label: "Snöflinga", keywords: ["snö", "vinter", "is", "kold", "frys"] },
  { emoji: "🔥", label: "Eld", keywords: ["eld", "brand", "het", "varmt", "fire"] },
  { emoji: "💧", label: "Droppe", keywords: ["vatten", "droppe", "regn", "blå"] },
  { emoji: "🌊", label: "Våg", keywords: ["hav", "ocean", "våg", "vatten", "blå"] },
  { emoji: "🏔️", label: "Berg", keywords: ["berg", "fjäll", "natur", "vandring", "höjd"] },

  // Djur
  { emoji: "🐾", label: "Tassar", keywords: ["tassar", "djur", "hund", "katt", "husdjur"] },
  { emoji: "🐶", label: "Hund", keywords: ["hund", "valp", "husdjur", "vovve"] },
  { emoji: "🐱", label: "Katt", keywords: ["katt", "kattunge", "husdjur", "misse"] },
  { emoji: "🐻", label: "Björn", keywords: ["björn", "djur", "brun", "nallebjörn"] },
  { emoji: "🦁", label: "Lejon", keywords: ["lejon", "djur", "safari", "kung"] },
  { emoji: "🐸", label: "Groda", keywords: ["groda", "djur", "grön", "hopp"] },
  { emoji: "🐦", label: "Fågel", keywords: ["fågel", "djur", "flyg", "kvitter"] },
  { emoji: "🦋", label: "Fjäril", keywords: ["fjäril", "djur", "blomma", "vacker"] },
  { emoji: "🐝", label: "Bi", keywords: ["bi", "humla", "honung", "insekt"] },
  { emoji: "🦄", label: "Enhörning", keywords: ["enhörning", "magi", "häst", "rosa"] },

  // Platser & byggnader
  { emoji: "🏥", label: "Sjukhus", keywords: ["sjukhus", "vård", "doktor", "läkare", "hälsa"] },
  { emoji: "🏫", label: "Skola", keywords: ["skola", "utbildning", "barn", "lärare"] },
  { emoji: "🏠", label: "Hus", keywords: ["hem", "hus", "bostad", "hemma"] },
  { emoji: "🏰", label: "Slott", keywords: ["slott", "kung", "prinsessa", "medeltid"] },
  { emoji: "🎡", label: "Pariserhjul", keywords: ["nöjespark", "pariserhjul", "kul", "resa"] },
  { emoji: "🏪", label: "Butik", keywords: ["butik", "affär", "handel", "köpa"] },
  { emoji: "🌍", label: "Jordklot", keywords: ["världen", "jord", "resa", "global"] },

  // Objekt & vardagsgrejer
  { emoji: "🛒", label: "Kundvagn", keywords: ["kundvagn", "handla", "shopping", "affär", "mat"] },
  { emoji: "🎁", label: "Present", keywords: ["present", "gåva", "födelsedag", "överraskning"] },
  { emoji: "🔑", label: "Nyckel", keywords: ["nyckel", "lås", "öppna", "dörr"] },
  { emoji: "📱", label: "Telefon", keywords: ["telefon", "mobil", "ring", "sms"] },
  { emoji: "💻", label: "Dator", keywords: ["dator", "laptop", "jobba", "skriva"] },
  { emoji: "✏️", label: "Penna", keywords: ["penna", "skriva", "rita", "anteckna"] },
  { emoji: "📷", label: "Kamera", keywords: ["kamera", "foto", "bild", "fotografera"] },
  { emoji: "⏰", label: "Väckarklocka", keywords: ["klocka", "tid", "väckning", "alarm", "morgon"] },
  { emoji: "💊", label: "Piller", keywords: ["medicin", "piller", "tablett", "hälsa"] },
  { emoji: "🩺", label: "Stetoskop", keywords: ["läkare", "stetoskop", "hälsa", "doktor"] },
  { emoji: "💉", label: "Spruta", keywords: ["spruta", "vaccination", "injektion", "läkare"] },
  { emoji: "🧸", label: "Nallebjörn", keywords: ["nalle", "leksak", "barn", "söt", "mjuk"] },
  { emoji: "🎈", label: "Ballong", keywords: ["ballong", "fest", "fira", "rosa"] },
  { emoji: "🎀", label: "Rosett", keywords: ["rosett", "band", "rosa", "present"] },
  { emoji: "📍", label: "Nål", keywords: ["nål", "plats", "karta", "markera"] },
  { emoji: "🗓️", label: "Kalender", keywords: ["kalender", "datum", "schema", "planering", "tid"] },
  { emoji: "🧹", label: "Kvast", keywords: ["städa", "kvast", "sopa", "rengöra"] },
  { emoji: "🪥", label: "Tandborste", keywords: ["tandborste", "tänder", "borsta", "hygien"] },
  { emoji: "🛁", label: "Badkar", keywords: ["badkar", "bad", "bada", "vatten"] },
  { emoji: "🧺", label: "Korg", keywords: ["tvätt", "korg", "kläder", "städa"] },
  { emoji: "🍽️", label: "Tallrik & bestick", keywords: ["mat", "äta", "tallrik", "middag", "lunch"] },
];
