export type EmojiEntry = {
  emoji: string;
  label: string;
  keywords: string[];
};

export const EMOJIS: EmojiEntry[] = [
  { emoji: "😀", label: "Glad", keywords: ["glad", "lycklig", "leende"] },
  { emoji: "😂", label: "Skratt", keywords: ["skratta", "rolig", "haha"] },
  { emoji: "😍", label: "Förälskad", keywords: ["kärlek", "älska", "förälskad"] },
  { emoji: "🥰", label: "Gullig", keywords: ["söt", "gullig", "hjärtan"] },
  { emoji: "😢", label: "Ledsen", keywords: ["ledsen", "gråta", "sorgsen"] },
  { emoji: "😡", label: "Arg", keywords: ["arg", "ilsken", "irriterad"] },
  { emoji: "🥳", label: "Firar", keywords: ["fest", "fira", "födelsedag"] },
  { emoji: "😴", label: "Trött", keywords: ["trött", "sova", "sömnig"] },
  { emoji: "🤒", label: "Sjuk", keywords: ["sjuk", "feber", "magont"] },
  { emoji: "😎", label: "Cool", keywords: ["cool", "solglasögon", "häftig"] },
  { emoji: "🤗", label: "Kram", keywords: ["kram", "varm", "omfamna"] },
  { emoji: "🤔", label: "Tänker", keywords: ["tänker", "funderar", "hmm"] },
  { emoji: "❤️", label: "Hjärta", keywords: ["hjärta", "kärlek", "röd"] },
  { emoji: "💙", label: "Blått hjärta", keywords: ["hjärta", "blå"] },
  { emoji: "💚", label: "Grönt hjärta", keywords: ["hjärta", "grön"] },
  { emoji: "💛", label: "Gult hjärta", keywords: ["hjärta", "gul"] },
  { emoji: "⭐", label: "Stjärna", keywords: ["stjärna", "guld", "bra"] },
  { emoji: "🌟", label: "Glänsande", keywords: ["stjärna", "glittra"] },
  { emoji: "✨", label: "Glitter", keywords: ["glitter", "magi", "skinande"] },
  { emoji: "🎉", label: "Konfetti", keywords: ["konfetti", "fest", "fira"] },
  { emoji: "🎊", label: "Festboll", keywords: ["fest", "fira", "ballong"] },
  { emoji: "👍", label: "Tumme upp", keywords: ["bra", "okej", "godkänd", "ja"] },
  { emoji: "👎", label: "Tumme ner", keywords: ["dåligt", "nej", "avslag"] },
  { emoji: "🙏", label: "Tack", keywords: ["tack", "be", "snälla"] },
  { emoji: "🏆", label: "Trofé", keywords: ["trofé", "vinst", "mästerskap"] },
  { emoji: "🥇", label: "Guld", keywords: ["guld", "etta", "vinnare", "medalj"] },
  { emoji: "💡", label: "Idé", keywords: ["idé", "lampa", "tips"] },
  { emoji: "🍕", label: "Pizza", keywords: ["pizza", "mat"] },
  { emoji: "🍔", label: "Hamburgare", keywords: ["hamburgare", "burger", "snabbmat"] },
  { emoji: "🌮", label: "Taco", keywords: ["taco", "mat", "mexikansk"] },
  { emoji: "🍣", label: "Sushi", keywords: ["sushi", "japansk", "fisk"] },
  { emoji: "🍜", label: "Nudlar", keywords: ["nudlar", "soppa", "asiatisk"] },
  { emoji: "🍰", label: "Tårtbit", keywords: ["tårta", "kaka", "bakelse"] },
  { emoji: "🎂", label: "Tårta", keywords: ["tårta", "födelsedag", "ljus"] },
  { emoji: "🧁", label: "Muffin", keywords: ["muffin", "kaka", "fika"] },
  { emoji: "🍫", label: "Choklad", keywords: ["choklad", "godis", "söt"] },
  { emoji: "🍦", label: "Glass", keywords: ["glass", "dessert", "sommar"] },
  { emoji: "🍎", label: "Äpple", keywords: ["äpple", "frukt", "röd"] },
  { emoji: "🍓", label: "Jordgubbe", keywords: ["jordgubbe", "bär", "frukt"] },
  { emoji: "🍌", label: "Banan", keywords: ["banan", "frukt", "gul"] },
  { emoji: "🍊", label: "Apelsin", keywords: ["apelsin", "citrus", "frukt"] },
  { emoji: "🍇", label: "Druvor", keywords: ["druvor", "bär", "frukt"] },
  { emoji: "🥕", label: "Morot", keywords: ["morot", "grönsak", "hälsa"] },
  { emoji: "🥦", label: "Broccoli", keywords: ["broccoli", "grönsak", "hälsa"] },
  { emoji: "🥑", label: "Avokado", keywords: ["avokado", "mat", "hälsa"] },
  { emoji: "🍳", label: "Ägg", keywords: ["ägg", "steka", "frukost"] },
  { emoji: "🥞", label: "Pannkakor", keywords: ["pannkakor", "frukost", "plättar"] },
  { emoji: "☕", label: "Kaffe", keywords: ["kaffe", "fika", "morgon"] },
  { emoji: "🍵", label: "Te", keywords: ["te", "varm", "fika"] },
  { emoji: "🧃", label: "Juice", keywords: ["juice", "dryck", "barn"] },
  { emoji: "🥛", label: "Mjölk", keywords: ["mjölk", "dryck", "barn"] },
  { emoji: "🥤", label: "Läsk", keywords: ["läsk", "dryck", "cola"] },
  { emoji: "⚽", label: "Fotboll", keywords: ["fotboll", "sport", "boll"] },
  { emoji: "🏊", label: "Simning", keywords: ["simma", "bad", "pool", "bassäng"] },
  { emoji: "🚴", label: "Cykling", keywords: ["cykling", "cykel", "träning"] },
  { emoji: "🏃", label: "Löpning", keywords: ["springa", "löpning", "jogga"] },
  { emoji: "🏋️", label: "Gym", keywords: ["gym", "träning", "styrka"] },
  { emoji: "⛷️", label: "Skidåkning", keywords: ["skida", "ski", "vinter", "fjäll"] },
  { emoji: "🏂", label: "Snowboard", keywords: ["snowboard", "vinter", "snö"] },
  { emoji: "🧘", label: "Yoga", keywords: ["yoga", "meditation", "lugn"] },
  { emoji: "🎵", label: "Musik", keywords: ["musik", "sång", "noter"] },
  { emoji: "🎸", label: "Gitarr", keywords: ["gitarr", "musik", "rock"] },
  { emoji: "🎹", label: "Piano", keywords: ["piano", "musik", "tangenter"] },
  { emoji: "🎮", label: "Spel", keywords: ["spel", "gaming", "datorspel"] },
  { emoji: "🎭", label: "Teater", keywords: ["teater", "drama", "skådespel"] },
  { emoji: "🎨", label: "Konst", keywords: ["konst", "måla", "kreativ"] },
  { emoji: "🎯", label: "Mål", keywords: ["mål", "träffa", "dart"] },
  { emoji: "🎪", label: "Cirkus", keywords: ["cirkus", "show", "tält"] },
  { emoji: "🎓", label: "Examen", keywords: ["examen", "skola", "student", "plugg"] },
  { emoji: "🏖️", label: "Strand", keywords: ["strand", "semester", "sommar", "bad"] },
  { emoji: "📚", label: "Böcker", keywords: ["böcker", "läsa", "studera", "bibliotek"] },
  { emoji: "✈️", label: "Flygplan", keywords: ["flyg", "resa", "semester"] },
  { emoji: "🚗", label: "Bil", keywords: ["bil", "köra", "transport"] },
  { emoji: "🚂", label: "Tåg", keywords: ["tåg", "järnväg", "resa"] },
  { emoji: "🚢", label: "Båt", keywords: ["båt", "kryssning", "hav", "färja"] },
  { emoji: "🚲", label: "Cykel", keywords: ["cykel", "cykla", "transport"] },
  { emoji: "🌿", label: "Växt", keywords: ["natur", "växt", "grön", "ört"] },
  { emoji: "🌸", label: "Blomma", keywords: ["blomma", "rosa", "vår"] },
  { emoji: "🌻", label: "Solros", keywords: ["solros", "blomma", "gul", "sommar"] },
  { emoji: "🍀", label: "Klöver", keywords: ["klöver", "tur", "lycka"] },
  { emoji: "🍁", label: "Löv", keywords: ["löv", "höst", "orange"] },
  { emoji: "🌲", label: "Träd", keywords: ["träd", "skog", "gran"] },
  { emoji: "🌴", label: "Palm", keywords: ["palm", "tropisk", "semester"] },
  { emoji: "🌈", label: "Regnbåge", keywords: ["regnbåge", "färger", "regn"] },
  { emoji: "🌞", label: "Sol", keywords: ["sol", "sommar", "värme"] },
  { emoji: "🌙", label: "Måne", keywords: ["måne", "natt", "halvmåne"] },
  { emoji: "❄️", label: "Snö", keywords: ["snö", "vinter", "is", "kold"] },
  { emoji: "🔥", label: "Eld", keywords: ["eld", "brand", "het"] },
  { emoji: "💧", label: "Vatten", keywords: ["vatten", "droppe", "regn"] },
  { emoji: "🌊", label: "Hav", keywords: ["hav", "ocean", "våg"] },
  { emoji: "🏔️", label: "Berg", keywords: ["berg", "fjäll", "vandring"] },
  { emoji: "🐾", label: "Tassar", keywords: ["tassar", "djur", "hund", "katt"] },
  { emoji: "🐶", label: "Hund", keywords: ["hund", "valp", "vovve"] },
  { emoji: "🐱", label: "Katt", keywords: ["katt", "kattunge", "misse"] },
  { emoji: "🐻", label: "Björn", keywords: ["björn", "nallebjörn"] },
  { emoji: "🦁", label: "Lejon", keywords: ["lejon", "safari"] },
  { emoji: "🐦", label: "Fågel", keywords: ["fågel", "flyg", "kvitter"] },
  { emoji: "🦋", label: "Fjäril", keywords: ["fjäril", "blomma", "vacker"] },
  { emoji: "🦄", label: "Enhörning", keywords: ["enhörning", "magi", "häst"] },
  { emoji: "🏥", label: "Sjukhus", keywords: ["sjukhus", "vård", "läkare"] },
  { emoji: "🏫", label: "Skola", keywords: ["skola", "utbildning", "barn"] },
  { emoji: "🏠", label: "Hus", keywords: ["hem", "hus", "bostad"] },
  { emoji: "🏰", label: "Slott", keywords: ["slott", "kung", "prinsessa"] },
  { emoji: "🛒", label: "Kundvagn", keywords: ["handla", "shopping", "affär", "mat"] },
  { emoji: "🎁", label: "Present", keywords: ["present", "gåva", "födelsedag"] },
  { emoji: "🔑", label: "Nyckel", keywords: ["nyckel", "lås", "öppna"] },
  { emoji: "📱", label: "Telefon", keywords: ["telefon", "mobil", "ring"] },
  { emoji: "💻", label: "Dator", keywords: ["dator", "laptop", "jobba"] },
  { emoji: "✏️", label: "Penna", keywords: ["penna", "skriva", "rita"] },
  { emoji: "📷", label: "Kamera", keywords: ["kamera", "foto", "fotografera"] },
  { emoji: "⏰", label: "Klocka", keywords: ["klocka", "tid", "alarm", "morgon"] },
  { emoji: "💊", label: "Medicin", keywords: ["medicin", "piller", "tablett"] },
  { emoji: "🩺", label: "Läkare", keywords: ["läkare", "stetoskop", "hälsa"] },
  { emoji: "🧸", label: "Nalle", keywords: ["nalle", "leksak", "barn"] },
  { emoji: "🎈", label: "Ballong", keywords: ["ballong", "fest", "fira"] },
  { emoji: "🎀", label: "Rosett", keywords: ["rosett", "band", "present"] },
  { emoji: "🗓️", label: "Kalender", keywords: ["kalender", "datum", "schema", "planering"] },
  { emoji: "🧹", label: "Städa", keywords: ["städa", "kvast", "rengöra"] },
  { emoji: "🛁", label: "Bad", keywords: ["badkar", "bad", "bada"] },
  { emoji: "🍽️", label: "Mat", keywords: ["mat", "äta", "middag", "lunch"] },
  { emoji: "🌍", label: "Världen", keywords: ["världen", "jord", "resa", "global"] },
];
